device/esp_tinyusb:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class/uvc/usb_host_uvc/examples/camera_display:
  enable:
    - if: (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 3)
      reason: This example uses esp_lcd API introduced in v5.3

# Host tests
host/class/cdc/usb_host_cdc_acm/host_test:
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
      reason: USB mocks are run only for the latest version of IDF

host/class/hid/usb_host_hid/host_test:
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
      reason: USB mocks are run only for the latest version of IDF

host/class/uvc/usb_host_uvc/host_test:
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
      reason: USB mocks are run only for the latest version of IDF

host/class/uac/usb_host_uac/host_test:
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
      reason: USB mocks are run only for the latest version of IDF
