device/esp_tinyusb:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class/uvc/usb_host_uvc/examples/camera_display:
  enable:
    - if: (IDF_VERSION >= "5.3.0")
      reason: This example uses esp_lcd API introduced in v5.3

# Host tests
.host_test_enable_rules: &host_test_enable_rules
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION >= "6.0.0")
      reason: USB mocks are run only for the latest version of IDF

host/class/cdc/usb_host_cdc_acm/host_test:
  <<: *host_test_enable_rules

host/class/hid/usb_host_hid/host_test:
  <<: *host_test_enable_rules

host/class/uvc/usb_host_uvc/host_test:
  <<: *host_test_enable_rules

host/class/uac/usb_host_uac/host_test:
  <<: *host_test_enable_rules
