# Manifest file for build_idf_examples.yml CI workflow

examples/peripherals/usb/device:
  enable:
    - if: (IDF_VERSION >= "6.0.0")
      reason: Device examples have been updated to use esp_tinyusb 2.x only on esp-idf latest for now, TODO IDF-14282
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1

examples/peripherals/usb/device/tusb_ncm:
  enable:
    - if: (IDF_VERSION >= "6.0.0")
      reason: Device examples have been updated to use esp_tinyusb 2.x only on esp-idf latest for now, TODO IDF-14282
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1 or SOC_WIFI_SUPPORTED != 1

examples/peripherals/usb/host:
  enable:
    - if: (IDF_VERSION >= "5.4.0")
      reason: Run USB Host examples with overridden (esp-usb) USB component only for service releases
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1

examples/peripherals/usb/host/uvc:
  enable:
    - if: (IDF_VERSION >= "5.5.0")
      reason: Run UVC example starts using UVC driver 2.0 only on IDF version 5.5
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1
