# Manifest file for build_idf_examples.yml CI workflow

examples/peripherals/usb/device:
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1

examples/peripherals/usb/device/tusb_ncm:
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1 or SOC_WIFI_SUPPORTED != 1

examples/peripherals/usb/host:
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1

examples/peripherals/usb/host/uvc:
  enable:
    - if: (IDF_VERSION >= "5.5.0")
      reason: Run UVC example starts using UVC driver 2.0 only on IDF version 5.5
  disable:
    - if: SOC_USB_OTG_SUPPORTED != 1
