# SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0
# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year
start_year = 2025

if current_year == start_year:
    copyright = '{}, Espressif Systems (Shanghai) Co., Ltd'.format(start_year)
else:
    copyright = '{} - {}, Espressif Systems (Shanghai) Co., Ltd'.format(start_year, current_year)

# General information about the project.
project = u'ESP-USB Programming Guide'
author = u'Espressif Systems'
pdf_title = u'ESP-USB Programming Guide'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
