# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/usb/test_apps:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1
  depends_components:
    - usb
  depends_filepatterns:
    - components/hal/usb*.c
    - components/hal/esp32*/include/hal/usb*.h
