name: Build ESP-IDF USB examples

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idf_ver:
          [
            "release-v5.1",
            "release-v5.2",
            "release-v5.3",
            "release-v5.4",
            "release-v5.5",
            "latest",
          ]
#        idf_example:
#          [
#            "device",
#            "host",
#          ]
#        exclude:
#          - idf_ver: "release-v5.1"
#            idf_example: "host"
#          - idf_ver: "release-v5.2"
#            idf_example: "host"
#          - idf_ver: "release-v5.3"
#            idf_example: "host"
#        include:
#          - idf_example: "device"
#            override_component: "esp_tinyusb"
#            override_path: "device/esp_tinyusb"
#            example_path: "examples/peripherals/usb/device"
#          - idf_example: "host"
#            override_component: "usb"
#            override_path: "host/usb"
#            example_path: "examples/peripherals/usb/host"
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    env:
      CONFIG_PATH: ${{ github.workspace }}/.github/ci/.examples_build.toml
      MANIFEST_PATH: ${{ github.workspace }}/.github/ci/.examples-rules.yml

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Install Python deps
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager>=2.1.2 idf-build-apps==2.4.3 pyyaml --upgrade
      - name: Build ESP-IDF ${{ matrix.idf_ver }} USB ${{ matrix.idf_example }} examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          #python .github/ci/override_managed_component.py ${{ matrix.override_component }} ${{ matrix.override_path }} ${IDF_PATH}/${{ matrix.example_path }}/*

          python .github/ci/override_managed_component.py esp_tinyusb device/esp_tinyusb ${IDF_PATH}/examples/peripherals/usb/device/*
          python .github/ci/override_managed_component.py usb host/usb ${IDF_PATH}/examples/peripherals/usb/host/*
          cd ${IDF_PATH}

          idf-build-apps find --config-file ${CONFIG_PATH} --manifest-file ${MANIFEST_PATH}
          idf-build-apps build --config-file ${CONFIG_PATH} --manifest-path ${MANIFEST_PATH}
