name: Build ESP-IDF USB examples

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idf_ver:
          [
            "release-v5.1",
            "release-v5.2",
            "release-v5.3",
            "release-v5.4",
            "release-v5.5",
            "latest",
          ]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    env:
      CONFIG_PATH: ${{ github.workspace }}/.github/ci/build_idf_examples/.idf_build_examples.toml
      MANIFEST_PATH: ${{ github.workspace }}/.github/ci/build_idf_examples/.build-test-rules.yml

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Install Python deps
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager>=2.1.2 idf-build-apps==2.4.3 pyyaml --upgrade
      - name: Build ESP-IDF ${{ matrix.idf_ver }} USB examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh

          # Uncomment the below line to enable device tests
          #python .github/ci/override_managed_component.py esp_tinyusb device/esp_tinyusb ${IDF_PATH}/examples/peripherals/usb/device/*
          python .github/ci/override_managed_component.py usb host/usb ${IDF_PATH}/examples/peripherals/usb/host/*
          cd ${IDF_PATH}

          idf-build-apps find --config-file ${CONFIG_PATH} --manifest-file ${MANIFEST_PATH}
          idf-build-apps build --config-file ${CONFIG_PATH} --manifest-file ${MANIFEST_PATH}
