# This workflow builds esp-idf examples:
#
#   - usb device examples: with overridden esp_tinyusb from esp-usb/device/esp_tinyusb
#     - Only IDF Latest
#
#   - usb host examples:
#     - Overridden usb component from esp-usb/host/usb and overridden class drivers from esp-usb/host/class
#       - Only service IDF releases
#     - Overridden class drivers from esp-usb/host/class
#       - All (service + maintenance IDF releases)

name: Build ESP-IDF USB examples

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        idf_ver:
          [
            "release-v5.1",
            "release-v5.2",
            "release-v5.3",
            "release-v5.4",
            "release-v5.5",
            "latest",
          ]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    env:
      CONFIG_PATH: ${{ github.workspace }}/.github/ci/.idf_build_examples_config.toml
      MANIFEST_PATH: ${{ github.workspace }}/.github/ci/.idf-build-examples-rules.yml
      EXAMPLES_PATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Install Python deps
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager>=2.1.2 idf-build-apps==2.12.2 pyyaml --upgrade
      - name: Setup IDF Examples path
        run: echo "EXAMPLES_PATH=${IDF_PATH}/examples/peripherals/usb" >> $GITHUB_ENV
      - name: Override device component
        if: contains('latest', matrix.idf_ver)
        run: |
          . ${IDF_PATH}/export.sh
          python .github/ci/override_managed_component.py esp_tinyusb device/esp_tinyusb ${{ env.EXAMPLES_PATH }}/device/*
      - name: Override class components
        run: |
          . ${IDF_PATH}/export.sh

          # cdc
          python .github/ci/override_managed_component.py usb_host_cdc_acm host/class/cdc/usb_host_cdc_acm ${{ env.EXAMPLES_PATH }}/host/cdc

          # hid
          python .github/ci/override_managed_component.py usb_host_hid host/class/hid/usb_host_hid ${{ env.EXAMPLES_PATH }}/host/hid

          # msc
          python .github/ci/override_managed_component.py usb_host_msc host/class/msc/usb_host_msc ${{ env.EXAMPLES_PATH }}/host/msc

          # uac
          python .github/ci/override_managed_component.py usb_host_uac host/class/uac/usb_host_uac ${{ env.EXAMPLES_PATH }}/host/uac

          # uvc
          python .github/ci/override_managed_component.py usb_host_uvc host/class/uvc/usb_host_uvc ${{ env.EXAMPLES_PATH }}/host/uvc

      - name: Override usb component
        if: contains('release-v5.4 release-v5.5 latest', matrix.idf_ver)
        run: |
          # Override usb component only for maintenance releases
          . ${IDF_PATH}/export.sh
          python .github/ci/override_managed_component.py usb host/usb ${{ env.EXAMPLES_PATH }}/host/*
      - name: Build ESP-IDF ${{ matrix.idf_ver }} USB examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          cd ${IDF_PATH}

          # Export compiler flags
          export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
          export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
          export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"

          idf-build-apps find --config-file ${CONFIG_PATH} --manifest-file ${MANIFEST_PATH}
          idf-build-apps build --config-file ${CONFIG_PATH} --manifest-file ${MANIFEST_PATH}
