name: Build and Run USB Host test

on:
  schedule:
    - cron: '0 0 * * SAT' # Saturday midnight
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["latest"]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build USB Test Application
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-build-apps==2.4.3 --upgrade
          idf-build-apps find --target linux
          idf-build-apps build --target linux
          ./host/class/cdc/usb_host_cdc_acm/host_test/build_linux/host_test_usb_cdc.elf
          ./host/class/uvc/usb_host_uvc/host_test/build_linux/host_test_usb_uvc.elf
          ./host/class/hid/usb_host_hid/host_test/build_linux/host_test_usb_hid.elf
